### ISSUE TITLE
Rails 5 cannot load such script coffeescript

### ISSUE THREAD

**Issue by Startouf** [apneadiving/Google-Maps-for-Rails#511]
It seems that adding `gem 'gmaps4rails'` to my gemfile breaks the asset pipeline.

> LoadError in StaticPagesController#home
> cannot load such file -- coffee_script

I am not using CoffeeScript anywhere else in my application as far as I know.

The relevant part of my full stack trace:

```
activesupport (5.0.0.beta3) lib/active_support/dependencies.rb:302:in `require'
activesupport (5.0.0.beta3) lib/active_support/dependencies.rb:302:in `block in require'
activesupport (5.0.0.beta3) lib/active_support/dependencies.rb:268:in `load_dependency'
activesupport (5.0.0.beta3) lib/active_support/dependencies.rb:302:in `require'
sprockets (3.6.0) lib/sprockets/autoload/coffee_script.rb:1:in `<top (required)>'
sprockets (3.6.0) lib/sprockets/coffee_script_processor.rb:15:in `cache_key'
sprockets (3.6.0) lib/sprockets/coffee_script_processor.rb:20:in `call'
sprockets (3.6.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.6.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.6.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.6.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.6.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.6.0) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.6.0) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.6.0) lib/sprockets/loader.rb:44:in `load'
sprockets (3.6.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.6.0) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.6.0) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.6.0) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.6.0) lib/sprockets/utils.rb:183:in `dfs'
sprockets (3.6.0) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.6.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.6.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.6.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.6.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.6.0) lib/sprockets/loader.rb:134:in `load_from_unloaded'
sprockets (3.6.0) lib/sprockets/loader.rb:60:in `block in load'
sprockets (3.6.0) lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
sprockets (3.6.0) lib/sprockets/loader.rb:44:in `load'
sprockets (3.6.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.6.0) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.6.0) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.6.0) lib/sprockets/base.rb:66:in `find_asset'
sprockets (3.6.0) lib/sprockets/base.rb:73:in `find_all_linked_assets'
sprockets (3.6.0) lib/sprockets/manifest.rb:142:in `block in find'
sprockets (3.6.0) lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
sprockets (3.6.0) lib/sprockets/path_utils.rb:223:in `block in stat_tree'
sprockets (3.6.0) lib/sprockets/path_utils.rb:207:in `block in stat_directory'
sprockets (3.6.0) lib/sprockets/path_utils.rb:204:in `each'
sprockets (3.6.0) lib/sprockets/path_utils.rb:204:in `stat_directory'
sprockets (3.6.0) lib/sprockets/path_utils.rb:222:in `stat_tree'
sprockets (3.6.0) lib/sprockets/legacy.rb:105:in `each'
sprockets (3.6.0) lib/sprockets/legacy.rb:105:in `block in logical_paths'
sprockets (3.6.0) lib/sprockets/legacy.rb:104:in `each'
sprockets (3.6.0) lib/sprockets/legacy.rb:104:in `logical_paths'
sprockets (3.6.0) lib/sprockets/manifest.rb:140:in `find'
sprockets-rails (3.0.4) lib/sprockets/railtie.rb:49:in `each'
sprockets-rails (3.0.4) lib/sprockets/railtie.rb:49:in `map'
sprockets-rails (3.0.4) lib/sprockets/railtie.rb:49:in `precompiled_assets'
sprockets-rails (3.0.4) lib/sprockets/railtie.rb:34:in `asset_precompiled?'
sprockets-rails (3.0.4) lib/sprockets/railtie.rb:214:in `block (3 levels) in <class:Railtie>'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:345:in `call'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:345:in `precompiled?'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:349:in `raise_unless_precompiled_asset'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:323:in `digest_path'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:311:in `asset_path'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:89:in `block in resolve_asset_path'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:229:in `block in resolve_asset'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in `each'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in `detect'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228:in `resolve_asset'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:88:in `resolve_asset_path'
sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:78:in `compute_asset_path'
actionview (5.0.0.beta3) lib/action_view/helpers/asset_url_helper.rb:144:in `asset_path'
actionview (5.0.0.beta3) lib/action_view/helpers/asset_url_helper.rb:311:in `image_path'
actionview (5.0.0.beta3) lib/action_view/helpers/asset_tag_helper.rb:214:in `image_tag'
app/views/static_pages/home.html.erb:66:in `block in _app_views_static_pages_home_html_erb__2007790927_56730080'
```

**Comment by apneadiving** [comment]
Yeah, the gem requires coffeescript. 
An alternative could be to use the js version, you can find code here: https://cdnjs.cloudflare.com/ajax/libs/gmaps4rails/2.1.2/gmaps4rails.min.js
